server:
  port: 1111
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    #prefer-ip-address: true #使用IP定义注册中心地址
  client:
    registerWithEureka: false  #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/