server:
  port: 1113

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer3
    #prefer-ip-address: true #使用IP定义注册中心地址
  client:
    #registerWithEureka: false  #是否向服务注册中心注册自己
    #fetchRegistry: false #是否检索服务
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/